server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
    max-threads: 50
    max-connections: 50
    min-spare-threads: 20
  max-http-header-size: 51200000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.104.66:3306/facesun?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
    mvc:
      mvc:
    static-path-pattern: /**
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#fds客户端
fds:
  ip: 124.207.133.150
  username: root
  password: shenlingfds
  threshold: 75

